apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-service
  template:
    metadata:
      labels:
        app: visit-service
    spec:
      containers:
        - name: visit-service
          image: grupo1/visit-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: OTEL_SERVICE_NAME
              value: "visit-service"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4318"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
---
apiVersion: v1
kind: Service
metadata:
  name: visit-service
spec:
  selector:
    app: visit-service
  ports:
    - port: 8082
      targetPort: 8082
